src/com/ait/jsf/AdditionalInfoBean.java
/*
 * Joe O'Regan
 * A00258304
 */
package com.ait.jsf;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;

@ManagedBean(name = "additionalInfoBean")
@SessionScoped
public class AdditionalInfoBean implements Serializable {
	private static final long serialVersionUID = 1L;
	// private String previousPage;
	private String originalPage;

	public String back() {

		FacesContext ctx = FacesContext.getCurrentInstance();

		ExternalContext extCtx = ctx.getExternalContext();

		HttpServletRequest req = (HttpServletRequest) extCtx.getRequest();

		originalPage = req.getRequestURI();

		return "AdditionalInfo";
	}

	public String getOriginalPage() {
		return originalPage;
	}

	public void setOriginalPage(String originalPage) {
		this.originalPage = originalPage;
	}
}

src/com/ait/jsf/CartBean.java
/*
 * Joe O'Regan
 * A00258304
 */
package com.ait.jsf;

import java.io.Serializable;
import java.util.ArrayList;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean(name = "cartBean")
@SessionScoped
public class CartBean implements Serializable {
	private static final long serialVersionUID = 1L;
	private ArrayList<Item> items;
	private String name;
	private String address;

	public CartBean() {
		items = new ArrayList<Item>();
	}

	public ArrayList<Item> getItems() {
		return items;
	}

	public void setItems(ArrayList<Item> items) {
		this.items = items;
	}

	public void addItemToCart(int productID, int quantity) {
		Item item = new Item(productID, quantity);
		items.add(item);
	}

	public void removeItemFromCart(int productID) {
		Item item = new Item(productID);

		for (Item searchItem : items) {
			if (searchItem.equals(item)) {
				items.remove(searchItem);
				break;
			}
		}
	}

	public int getItemCount() {
		return items.size();
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}
}

src/com/ait/jsf/CheckoutBean.java
/*
 * Joe O'Regan
 * A00258304
 */
package com.ait.jsf;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean(name = "checkoutBean")
@SessionScoped
public class CheckoutBean implements Serializable {
	private static final long serialVersionUID = 1L;

	public String myCheckoutHandler() {
		// Get the CartBean instance.
		CartBean cart = Helper.getBean("cartBean", CartBean.class);

		if (cart.getItemCount() > 5) {
			return "CheckoutBulk";
		}
		return "Checkout";
	}
}

src/com/ait/jsf/ShopBean.java
/*
 * Joe O'Regan
 * A00258304
 */
package com.ait.jsf;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;
//import javax.faces.bean.RequestScoped;
import javax.faces.bean.SessionScoped;

@ManagedBean(name = "shopBean")
@SessionScoped
// @RequestScoped
public class ShopBean implements Serializable {
	private static final long serialVersionUID = 1L;
	private int productID;
	private int quantity;

	public ShopBean() {
		this.productID = 0;
		this.quantity = 0;
	}

	public int getProductID() {
		return productID;
	}

	public void setProductID(int productID) {
		this.productID = productID;
	}

	public int getQuantity() {
		return quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	// OK - Handle "Add to Cart" button click event
	public String addHandler() {
		CartBean cart = Helper.getBean("cartBean", CartBean.class);
		cart.addItemToCart(productID, quantity);
		this.quantity = 0;
		return null;
	}

	// OK - Handle "Remove" button click event
	public String removeHandler() {
		CartBean cart = Helper.getBean("cartBean", CartBean.class);
		cart.removeItemFromCart(productID);
		return null;
	}
}

WebContent/AdditionalInfo.xhtml
<!-- 
Joe O'Regan
A00258304
Team Project JSF Lab
 -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">   
<h:head>
	<title>Additional Info page</title>
	<h:outputStylesheet name="stylesheet.css" library="css"/>
</h:head>

<h:body>
	<f:view>	
		<h2 class="heading">Additional Information</h2>
		
		<h:form>
			<h:outputText value="Blah" /><br/>
			<h:outputText value="Blah" /><br/>
			<h:outputText value="Orders will be dispatched in the next 48 hours, or 24 hours for bulk orders" />
			<br/><br/>
	        <h:commandButton value="Home" action="Home" styleClass="ActionButton"/>	        
	    </h:form>	    	    
	</f:view>
	
	<a href="${additionalInfoBean.originalPage}">
		Back to ${additionalInfoBean.originalPage}
	</a>
</h:body>
</html>

WebContent/Checkout.xhtml
<!-- 
Joe O'Regan
A00258304
Team Project JSF Lab
 -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">   
<h:head>
	<title>Checkout page</title>
	<h:outputStylesheet name="stylesheet.css" library="css"/>
</h:head>

<h:body>
	<f:view>	
		<h2 class="heading">Order confirmation</h2>
		
	    <h:form>
			<h:outputText value="Customer: #{cartBean.name}" /><br/>
			<h:outputText value="Dispatch address: #{cartBean.address}" />
			<br /><br/>
			<h:outputText value="Your #{cartBean.itemCount} item(s) will be dispatched in the next 48 hours" />
			<br/><br/>
	        <!-- h:commandButton value="Home" action="Home" styleClass="ActionButton"/ -->  
	        <a href="Home.jsf">Home</a><br/><br/>      
	    </h:form>
	</f:view>
	
	<div>     
	    <h:form>	    
			<!-- h:commandLink action="AdditionalInfo">Additional Info</h:commandLink -->  
			<h:commandLink action="#{additionalInfoBean.back}">Additional Info</h:commandLink>       
	    </h:form>	    
	</div>
</h:body>
</html>

WebContent/CheckoutBulk.xhtml
<!-- 
Joe O'Regan
A00258304
Team Project JSF Lab
 -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">   
<h:head>
	<title>Bulk checkout page</title>
	<h:outputStylesheet name="stylesheet.css" library="css"/>
</h:head>

<h:body>
	<f:view>	
		<h2 class="heading">Order confirmation for Bulk Order</h2>
		
	    <h:form>
			<h:outputText value="Customer: #{cartBean.name}" /><br/>
			<h:outputText value="Dispatch address: #{cartBean.address}" />
			<br /><br/>
			<h:outputText value="Your #{cartBean.itemCount} item(s) will be dispatched in the next 24 hours" />
			<br/><br/>
	        <!-- h:commandButton value="Home" action="Home" styleClass="ActionButton"/ -->  
	        <a href="Home.jsf">Home</a><br/><br/>
	    </h:form>
	</f:view>
	
	<div>     
	    <h:form>	    
			<!-- h:commandLink action="AdditionalInfo">Additional Info</h:commandLink -->  
			<h:commandLink action="#{additionalInfoBean.back}">Additional Info</h:commandLink>       
	    </h:form>	    
	</div>
</h:body>
</html>

WebContent/Home.xhtml
<!-- 
Joe O'Regan
A00258304
Team Project JSF Lab
 -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">   
<h:head>
	<title>Home page</title>
	<h:outputStylesheet name="stylesheet.css" library="css"/>
</h:head>

<h:body>
	<f:view>	
	    <h:form>
	        <h1><h:outputText value="Welcome to my online shop!"/></h1>
	        
	        <!-- h:graphicImage value="images/Hello.jpg" /-->
			<h:outputLabel>Name:</h:outputLabel>
			<h:inputText id="name" value="#{cartBean.name}" title="Enter Your Name" />
			<br />
			<h:outputLabel>Address:</h:outputLabel>
			<h:inputText id="address" value="#{cartBean.address}" title="Address: " />
			<br />
	        <h:commandButton value="Start shopping!" action="shop" styleClass="ActionButton"/>	        
	    </h:form>
	</f:view>
	
	<div>     
	    <h:form>	    
			<!-- h:commandLink action="AdditionalInfo">Additional Info</h:commandLink -->  
			<h:commandLink action="#{additionalInfoBean.back}">Additional Info</h:commandLink>    
	    </h:form>	    
	</div>
</h:body>
</html>

WebContent/shop.xhtml
<!-- 
Joe O'Regan
A00258304
Team Project JSF Lab
 -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
	
<h:head>
	<title>Shopping page</title>
	<h:outputStylesheet name="stylesheet.css" library="css" />
</h:head>

<h:body>
	<h:form>
		<h2 class="heading">Products</h2>
		
		<h:selectOneListbox id="productsListBox" value="#{shopBean.productID}"
			onchange="this.form.submit();" title="Products you can buy online">
			<f:selectItem itemValue="0" itemLabel="iPod" />
			<f:selectItem itemValue="1" itemLabel="iStation" />
			<f:selectItem itemValue="2" itemLabel="hdc Diamond phone" />
			<f:selectItem itemValue="3" itemLabel="HD TV" />
			<f:selectItem itemValue="4" itemLabel="Wireless Speakers" />
			<f:selectItem itemValue="5" itemLabel="Blue Ray DVD Player" />
		</h:selectOneListbox>
		<br />
	</h:form>

	<f:view>
		<h:form>
			<h2 class="heading">Manage My Cart</h2>
			
			<h:outputLabel>Product ID:</h:outputLabel>		
			<h:inputText id="productID" size="3" value="#{shopBean.productID}"
				readonly="true" title="ID for your selected product" />
			<br />		
			<h:outputLabel>Quantity:</h:outputLabel>		
			<h:inputText id="quantity" size="3" value="#{shopBean.quantity}"
				title="Tell us how many you want!" onchange="this.form.submit();" />
			<br />
		</h:form>
	</f:view>

	<h:form>
		<h:commandButton id="add" class="ActionButton"
			action="#{shopBean.addHandler}" value="Add to Cart"
			title="Add product to your shopping cart" /> &nbsp;&nbsp;		
		<h:commandButton id="remove" styleClass="ActionButton"
			action="#{shopBean.removeHandler}" value="Remove"
			title="Remove product from your shopping cart" /> &nbsp;&nbsp;
		
		<h:commandButton value="Check Out" id="checkout" action="#{checkoutBean.myCheckoutHandler}"
			styleClass="ActionButton" />
	</h:form>
	
	<h2 class="heading">Contents of cart</h2>

	<h:dataTable value="#{cartBean.items}" var="row">
		<h:column>
			<h:outputText value="ID: #{row.productID}" />
		</h:column>		
		<h:column>
			<h:outputText value="Qty: #{row.quantity}" />
		</h:column>
	</h:dataTable>

	<div>     
	    <h:form>	    
			<!-- h:commandLink action="AdditionalInfo">Additional Info</h:commandLink -->  
			<h:commandLink action="#{additionalInfoBean.back}">Additional Info</h:commandLink>     
	    </h:form>	    
	</div>
	
</h:body>
</html>